name: Vercel

on:
  push:
    branches:
      - master

jobs:
  deploy-vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: yarn install 

      - name: Build Script
        run: yarn build
        
      - name: Run Script
        run: yarn start

      - name: Export Env
        run: mkdir registry/.vercel && echo "{\"orgId\":\"${{ secrets.VERCEL_ORGID }}\",\"projectId\":\"${{ secrets.VERCEL_PROJECTID }}\"}" > deploy/.vercel/project.json

      - name: Deploy Vercel
        run: npx vercel deploy registry --token ${{ secrets.VERCEL_TOKEN }} --prod --yes